import { PricingPlan } from '@/types';

export const recommendedPlanName = 'Standard';
export const pricingPlanData: PricingPlan[] = [
  {
    id: 'xDSR8nNAayVJ5P7oHXFwH',
    active: true,
    nickname: 'Free',
    amount: 0,
    currency: 'PLN',
    interval: 'month',
    metadata: {
      numberOfInquiries: 5,
      numberOfRecipients: 5,
      numberOfProducts: 10,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'naWzLP7o-Izh_I1vhWnAH',
    active: true,
    nickname: 'Free',
    amount: 0,
    currency: 'PLN',
    interval: 'year',
    metadata: {
      numberOfInquiries: 5,
      numberOfRecipients: 5,
      numberOfProducts: 10,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'fP9qYXsJ-9837mr9wvIEw',
    active: true,
    nickname: 'Basic',
    amount: 5000,
    currency: 'PLN',
    interval: 'month',
    metadata: {
      numberOfInquiries: 20,
      numberOfRecipients: 10,
      numberOfProducts: 20,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'W4qDyx3r34GYsUSSI_WoQ',
    active: true,
    nickname: 'Basic',
    amount: 45000,
    currency: 'PLN',
    interval: 'year',
    metadata: {
      numberOfInquiries: 20,
      numberOfRecipients: 10,
      numberOfProducts: 20,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: '1GEsUwc1DDJ5o-avUKJvB',
    active: true,
    nickname: 'Standard',
    amount: 8000,
    currency: 'PLN',
    interval: 'month',
    metadata: {
      numberOfInquiries: 40,
      numberOfRecipients: 20,
      numberOfProducts: 60,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'Gw_mF1W1JZjsSBgRqJF0U',
    active: true,
    nickname: 'Standard',
    amount: 72000,
    currency: 'PLN',
    interval: 'year',
    metadata: {
      numberOfInquiries: 40,
      numberOfRecipients: 20,
      numberOfProducts: 60,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'bNC5aP24ahnH7NcS6E_xe',
    active: true,
    nickname: 'Enterprise',
    amount: 14000,
    currency: 'PLN',
    interval: 'month',
    metadata: {
      numberOfInquiries: 80,
      numberOfRecipients: 40,
      numberOfProducts: 120,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
  {
    id: 'cQxE1BhhkyQzmTcy16n2e',
    active: true,
    nickname: 'Enterprise',
    amount: 124000,
    currency: 'PLN',
    interval: 'year',
    metadata: {
      numberOfInquiries: 80,
      numberOfRecipients: 40,
      numberOfProducts: 120,
      numberOfOffers: Infinity,
      numberOfOrders: Infinity,
    },
  },
];
